name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]
    paths:
      - "20*/**"

jobs:
  update-completion:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10.x"
      - name: Create local changes
        run: |
          pip install -r requirements.txt
          python generate_completion.py
      - name: Setup Git
        run: |
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Completed.md -f
          git commit -m "Updated The Completion Chart"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          branch: ${{ github.ref }}
